add chrony
omniosorg/omnios-build pull request #2467
Opened 2021-09-03 09:57 UTC by hadfl

2021-09-03 14:17 UTC, oetiker approved these changes

2021-09-03 15:25 UTC, citrus-it requested changes
The open-vm-tools smf manifest will need adjusting too.

2021-09-03 15:25 UTC, citrus-it commented on build/chrony/build.sh
> +        egrep -s "$flag 1" config.h || logerr "$flag not set"
```suggestion
       $EGREP -s "$flag 1" config.h || logerr "$flag not set"
```

2021-09-03 15:25 UTC, citrus-it commented on build/chrony/files/chrony.conf
> +! keyfile /etc/chrony.keys
```suggestion
! keyfile /etc/inet/chrony.keys
```

2021-09-03 15:25 UTC, citrus-it commented on build/chrony/files/chrony.conf
> +#
Remove block.

2021-09-03 15:25 UTC, citrus-it commented on build/chrony/files/chrony.conf
> +! hwtimestamp *
Remove

2021-09-03 15:25 UTC, citrus-it commented on build/chrony/files/chrony.conf
> +! rtcsync
Remove.

2021-09-03 16:02 UTC, tomww commented
May I ask to have added --enable-ntp-signd
(from https://wiki.samba.org/index.php/Time_Synchronisation#With_chrony_2:)
"chrony >= 3.0 from https://chrony.tuxfamily.org, compiled with enabled signed ntp support (**--enable-ntp-signd** when building chrony)"

That would greatly help in Samba Active Domain (e.g. SFEsamba410.spec) to have Windows clients get correct time.
It works like this: NTP packages are signed by the samba controller and sent to the clients. The socket is the connection between chrony and samba.

The path for the socket could be  /var/lib/samba/ntp_signd

Thank you!

2021-09-03 18:17 UTC, citrus-it commented
> May I ask to have added --enable-ntp-signd

It looks straightforward enough to include, I've added the option (and a disabled block to the example conf file that we ship).

2021-09-04 12:54 UTC, oetiker submitted a review, later dismissed

2021-09-07 21:54 UTC, citrus-it approved these changes

2021-09-07 21:55 UTC, merged